In [1]:
import numpy as np 
import pandas as pd
import os
from warnings import simplefilter
simplefilter(action="ignore", category=pd.errors.PerformanceWarning)

In [2]:
raw_df1 = pd.read_csv('UNSW-NB15_1.csv')
raw_df2 = pd.read_csv('UNSW-NB15_2.csv')
raw_df3 = pd.read_csv('UNSW-NB15_3.csv')
raw_df4 = pd.read_csv('UNSW-NB15_4.csv')

C:\Users\deeks\AppData\Local\Temp\ipykernel_13688\3083527476.py:1: DtypeWarning: Columns (1,3,47) have mixed types. Specify dtype option on import or set low_memory=False.
  raw_df1 = pd.read_csv('UNSW-NB15_1.csv')
C:\Users\deeks\AppData\Local\Temp\ipykernel_13688\3083527476.py:2: DtypeWarning: Columns (3,39,47) have mixed types. Specify dtype option on import or set low_memory=False.
  raw_df2 = pd.read_csv('UNSW-NB15_2.csv')

In [3]:
raw_df1.columns=[
'srcip',
'sport',
'dstip',
'dsport',
'proto',
'state',
'dur',
'sbytes',
'dbytes',
'sttl',
'dttl',
'sloss',
'dloss',
'service',
'Sload',
'Dload',
'Spkts',
'Dpkts',
'swin',
'dwin',
'stcpb',
'dtcpb',
'smeansz',
'dmeansz',
'trans_depth',
'res_bdy_len',
'Sjit',
'Djit',
'Stime',
'Ltime',
'Sintpkt',
'Dintpkt',
'tcprtt',
'synack',
'ackdat',
'is_sm_ips_ports',
'ct_state_ttl',
'ct_flw_http_mthd',
'is_ftp_login',
'ct_ftp_cmd',
'ct_srv_src',
'ct_srv_dst',
'ct_dst_ltm',
'ct_src_ ltm',
'ct_src_dport_ltm',
'ct_dst_sport_ltm',
'ct_dst_src_ltm',
'attack_cat',
'Label'
]
raw_df2.columns=[
'srcip',
'sport',
'dstip',
'dsport',
'proto',
'state',
'dur',
'sbytes',
'dbytes',
'sttl',
'dttl',
'sloss',
'dloss',
'service',
'Sload',
'Dload',
'Spkts',
'Dpkts',
'swin',
'dwin',
'stcpb',
'dtcpb',
'smeansz',
'dmeansz',
'trans_depth',
'res_bdy_len',
'Sjit',
'Djit',
'Stime',
'Ltime',
'Sintpkt',
'Dintpkt',
'tcprtt',
'synack',
'ackdat',
'is_sm_ips_ports',
'ct_state_ttl',
'ct_flw_http_mthd',
'is_ftp_login',
'ct_ftp_cmd',
'ct_srv_src',
'ct_srv_dst',
'ct_dst_ltm',
'ct_src_ ltm',
'ct_src_dport_ltm',
'ct_dst_sport_ltm',
'ct_dst_src_ltm',
'attack_cat',
'Label'
]
raw_df3.columns=[
'srcip',
'sport',
'dstip',
'dsport',
'proto',
'state',
'dur',
'sbytes',
'dbytes',
'sttl',
'dttl',
'sloss',
'dloss',
'service',
'Sload',
'Dload',
'Spkts',
'Dpkts',
'swin',
'dwin',
'stcpb',
'dtcpb',
'smeansz',
'dmeansz',
'trans_depth',
'res_bdy_len',
'Sjit',
'Djit',
'Stime',
'Ltime',
'Sintpkt',
'Dintpkt',
'tcprtt',
'synack',
'ackdat',
'is_sm_ips_ports',
'ct_state_ttl',
'ct_flw_http_mthd',
'is_ftp_login',
'ct_ftp_cmd',
'ct_srv_src',
'ct_srv_dst',
'ct_dst_ltm',
'ct_src_ ltm',
'ct_src_dport_ltm',
'ct_dst_sport_ltm',
'ct_dst_src_ltm',
'attack_cat',
'Label'
]
raw_df4.columns=[
'srcip',
'sport',
'dstip',
'dsport',
'proto',
'state',
'dur',
'sbytes',
'dbytes',
'sttl',
'dttl',
'sloss',
'dloss',
'service',
'Sload',
'Dload',
'Spkts',
'Dpkts',
'swin',
'dwin',
'stcpb',
'dtcpb',
'smeansz',
'dmeansz',
'trans_depth',
'res_bdy_len',
'Sjit',
'Djit',
'Stime',
'Ltime',
'Sintpkt',
'Dintpkt',
'tcprtt',
'synack',
'ackdat',
'is_sm_ips_ports',
'ct_state_ttl',
'ct_flw_http_mthd',
'is_ftp_login',
'ct_ftp_cmd',
'ct_srv_src',
'ct_srv_dst',
'ct_dst_ltm',
'ct_src_ ltm',
'ct_src_dport_ltm',
'ct_dst_sport_ltm',
'ct_dst_src_ltm',
'attack_cat',
'Label'
]

In [4]:
raw_df1['attack_cat'] = raw_df1['attack_cat'].replace(np.nan,"Benign")
raw_df2['attack_cat'] = raw_df2['attack_cat'].replace(np.nan,"Benign")
raw_df3['attack_cat'] = raw_df3['attack_cat'].replace(np.nan,"Benign")
raw_df4['attack_cat'] = raw_df4['attack_cat'].replace(np.nan,"Benign")
raw_df1['is_ftp_login'] = raw_df1['is_ftp_login'].replace(np.nan,0)
raw_df2['is_ftp_login'] = raw_df2['is_ftp_login'].replace(np.nan,0)
raw_df3['is_ftp_login'] = raw_df3['is_ftp_login'].replace(np.nan,0)
raw_df4['is_ftp_login'] = raw_df4['is_ftp_login'].replace(np.nan,0)
raw_df1['ct_flw_http_mthd'] = raw_df1['ct_flw_http_mthd'].replace(np.nan,0)
raw_df2['ct_flw_http_mthd'] = raw_df2['ct_flw_http_mthd'].replace(np.nan,0)
raw_df3['ct_flw_http_mthd'] = raw_df3['ct_flw_http_mthd'].replace(np.nan,0)
raw_df4['ct_flw_http_mthd'] = raw_df4['ct_flw_http_mthd'].replace(np.nan,0)
raw_df1['ct_ftp_cmd'] = raw_df1['ct_ftp_cmd'].replace(" ","0")
raw_df2['ct_ftp_cmd'] = raw_df2['ct_ftp_cmd'].replace(" ","0")
raw_df3['ct_ftp_cmd'] = raw_df3['ct_ftp_cmd'].replace(" ","0")
raw_df4['ct_ftp_cmd'] = raw_df4['ct_ftp_cmd'].replace(" ","0")

In [5]:
raw_df4

,srcip,sport,dstip,dsport,proto,state,dur,sbytes,dbytes,sttl,...,ct_ftp_cmd,ct_srv_src,ct_srv_dst,ct_dst_ltm,ct_src_ ltm,ct_src_dport_ltm,ct_dst_sport_ltm,ct_dst_src_ltm,attack_cat,Label
0,59.166.0.9,9685,149.171.126.2,80,tcp,FIN,5.864748,19410,1087890,31,...,0,3,1,4,4,1,1,1,Benign,0
1,59.166.0.2,1421,149.171.126.4,53,udp,CON,0.001391,146,178,31,...,0,3,5,2,7,1,1,4,Benign,0
2,59.166.0.2,21553,149.171.126.2,25,tcp,FIN,0.053948,37812,3380,31,...,0,1,1,4,7,1,1,3,Benign,0
3,59.166.0.8,45212,149.171.126.4,53,udp,CON,0.000953,146,178,31,...,0,2,5,2,1,1,1,2,Benign,0
4,59.166.0.0,59922,149.171.126.8,6881,tcp,FIN,8.633186,25056,1094788,31,...,0,9,7,2,3,2,1,6,Benign,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
440038,59.166.0.5,33094,149.171.126.7,43433,tcp,FIN,0.087306,320,1828,31,...,0,1,2,3,3,1,1,3,Benign,0
440039,59.166.0.7,20848,149.171.126.4,21,tcp,CON,0.365058,456,346,31,...,2,2,2,2,2,2,2,2,Benign,0
440040,59.166.0.3,21511,149.171.126.9,21,tcp,CON,6.335154,1802,2088,31,...,2,2,2,4,2,2,2,2,Benign,0
440041,59.166.0.9,35433,149.171.126.0,80,tcp,CON,2.200934,3498,166054,31,...,0,1,1,2,4,2,2,2,Benign,0
440042,175.45.176.0,17293,149.171.126.17,110,tcp,CON,0.942984,574,676,62,...,0,1,1,2,4,2,2,2,Exploits,1

In [6]:
raw_df1  = raw_df1.replace('-','unkown')
raw_df2  = raw_df2.replace('-','unkown')
raw_df3  = raw_df3.replace('-','unkown')
raw_df4  = raw_df4.replace('-','unkown')

In [7]:
raw_df4['ct_ftp_cmd'] = raw_df4['ct_ftp_cmd'].apply(pd.to_numeric)

In [8]:
main_df = pd.concat([raw_df1,raw_df2,raw_df3,raw_df4],ignore_index=True)

In [9]:
main_df['attack_cat'].unique()

array(['Benign', 'Exploits', 'Reconnaissance', 'DoS', 'Generic',
       'Shellcode', ' Fuzzers', 'Worms', 'Backdoors', 'Analysis',
       ' Reconnaissance ', 'Backdoor', ' Fuzzers ', ' Shellcode '],
      dtype=object)

In [10]:
a = main_df['dsport'].unique().tolist()

In [11]:
main_df['sport'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 2540043 entries, 0 to 2540042
Series name: sport
Non-Null Count    Dtype
--------------    -----
2540043 non-null  object
dtypes: object(1)
memory usage: 19.4+ MB

In [12]:
main_df['attack_cat'].replace(" Reconnaissance ","Reconnaissance",inplace=True)
main_df['attack_cat'].replace("Backdoors","Backdoor",inplace=True)
main_df['attack_cat'].replace(" Fuzzers ","Fuzzers",inplace=True)
main_df['attack_cat'].replace(" Fuzzers","Fuzzers",inplace=True)
main_df['attack_cat'].replace(" Shellcode ","Shellcode",inplace=True)

In [13]:
main_df['ct_ftp_cmd'] = main_df['ct_ftp_cmd'].apply(pd.to_numeric)

In [14]:
main_df

,srcip,sport,dstip,dsport,proto,state,dur,sbytes,dbytes,sttl,...,ct_ftp_cmd,ct_srv_src,ct_srv_dst,ct_dst_ltm,ct_src_ ltm,ct_src_dport_ltm,ct_dst_sport_ltm,ct_dst_src_ltm,attack_cat,Label
0,59.166.0.0,33661,149.171.126.9,1024,udp,CON,0.036133,528,304,31,...,0,2,4,2,3,1,1,2,Benign,0
1,59.166.0.6,1464,149.171.126.7,53,udp,CON,0.001119,146,178,31,...,0,12,8,1,2,2,1,1,Benign,0
2,59.166.0.5,3593,149.171.126.5,53,udp,CON,0.001209,132,164,31,...,0,6,9,1,1,1,1,1,Benign,0
3,59.166.0.3,49664,149.171.126.0,53,udp,CON,0.001169,146,178,31,...,0,7,9,1,1,1,1,1,Benign,0
4,59.166.0.0,32119,149.171.126.9,111,udp,CON,0.078339,568,312,31,...,0,2,4,2,3,1,1,2,Benign,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2540038,59.166.0.5,33094,149.171.126.7,43433,tcp,FIN,0.087306,320,1828,31,...,0,1,2,3,3,1,1,3,Benign,0
2540039,59.166.0.7,20848,149.171.126.4,21,tcp,CON,0.365058,456,346,31,...,2,2,2,2,2,2,2,2,Benign,0
2540040,59.166.0.3,21511,149.171.126.9,21,tcp,CON,6.335154,1802,2088,31,...,2,2,2,4,2,2,2,2,Benign,0
2540041,59.166.0.9,35433,149.171.126.0,80,tcp,CON,2.200934,3498,166054,31,...,0,1,1,2,4,2,2,2,Benign,0
2540042,175.45.176.0,17293,149.171.126.17,110,tcp,CON,0.942984,574,676,62,...,0,1,1,2,4,2,2,2,Exploits,1

In [15]:
main_df.to_csv('main_df.csv')